DEBUG = True
SECRET_KEY = '99e>\]zB9HpT(vp3'  # generated by http://passwordsgenerator.net/
EXPLAIN_TEMPLATE_LOADING = False
DATABASE_URI = 'sqlite:///app/database/thehandicrafter.db'
UPLOAD_FOLDER = 'app/static/uploads'
ALLOWED_EXTENSIONS = set(['txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif'])
